services:
  wspr:
    build: .
    container_name: tt-wspr
    restart: unless-stopped
    devices:
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - "8082:8082"
    volumes:
      - ./data:/data
    environment:
      WSPR_FREQUENCY: 14.0971M
      RTL_SAMPLE_RATE: 12000
      RTL_GAIN: auto
      RTL_PPM: 0
      WSPR_CYCLE_SECONDS: 114
      API_PORT: 8082
