services:
  aprs-web:
    build: .
    container_name: tt-aprs-web
    restart: unless-stopped
    ports:
      - "8091:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data:/data

  aprs-tiles:
    image: maptiler/tileserver-gl:latest
    container_name: tt-aprs-tiles
    restart: unless-stopped
    volumes:
      - ./data:/data:ro
    command: ["--file", "/data/map.mbtiles"]
    expose:
      - "8080"
